"""Test

Revision ID: a4eaa62c7cd4
Revises: 
Create Date: 2025-05-06 22:54:17.162721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4eaa62c7cd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('firstname', sa.String(length=256), nullable=True),
    sa.Column('lastname', sa.String(length=256), nullable=True),
    sa.Column('sex', sa.String(length=24), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_accounts_userid'), 'accounts', ['userid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_accounts_username'), 'accounts', ['username'], unique=True, schema='public')
    op.add_column('users', sa.Column('accountid', sa.UUID(), nullable=False))
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_public_users_accountid'), 'users', ['accountid'], unique=False, schema='public')
    op.create_foreign_key(None, 'users', 'accounts', ['accountid'], ['id'], source_schema='public', referent_schema='public', ondelete='restrict')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.drop_index(op.f('ix_public_users_accountid'), table_name='users', schema='public')
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.drop_column('users', 'accountid')
    op.drop_index(op.f('ix_public_accounts_username'), table_name='accounts', schema='public')
    op.drop_index(op.f('ix_public_accounts_userid'), table_name='accounts', schema='public')
    op.drop_table('accounts', schema='public')
    # ### end Alembic commands ###
