apiVersion: v1
kind: Service
metadata:
  name: {{ include "accountapi.fullname" . }}
  labels:
    {{- include "accountapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "accountapi.selectorLabels" . | nindent 4 }}
